version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432' # Mapeando a porta 5432 do container para a porta 5432 do host
    volumes:
      - db-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8081:80" # Mapeando a porta 80 do container para a porta 8080 do host
    environment:
      PGADMIN_DEFAULT_EMAIL: secret@gmail.com
      PGADMIN_DEFAULT_PASSWORD: secret-secret

volumes:
  db-data:
    driver: local
